source 'https://rubygems.org' do
  gem 'adsf'
  gem 'builder'
  gem 'coffee-script'
  gem 'guard'
  gem 'guard-shell'
  gem 'kramdown'
  gem 'nanoc'
  gem 'narray'
  gem 'nokogiri'
  gem 'rack'
  gem 'rubypants'
  gem 'sass'
  gem 'slim'
  gem 'tf-idf-similarity'
  gem 'yuicompressor'
end
